### ISSUE TITLE
no module named utils after installing the library

### ISSUE THREAD

**Issue by rakshitkathawate098** [tdjholder/bootstrap-difflib#1]
utils module in lib folder is not imported during installation of library, just add the FormatFactory class to the same file if possible

`
class FormatDict(dict):

    def __missing__(self, key):
        return '%(' + key + ')s'
`

**Comment by tdjholder** [comment]
Thanks for reporting, I'll take a look.

**Comment by tdjholder** [comment]
This has been fixed in v 0.0.2

**Comment by tdjholder** [comment]
v 0.0.3**
